services:
  alembic:
    build:
      context: .
      dockerfile: migrations/Dockerfile  # или другой путь, если alembic зависит от app
    image: alembic_image
    working_dir: /project
    volumes:
      - .:/project
    env_file:
      - "./.env"
    depends_on:
      - db_test
    

  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: api_image
    ports:
      - "8000:8000"
    env_file:
      - "./.env"
    depends_on:
      - db_test
      - redis

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    image: bot_image
    env_file:
      - "./.env"
    depends_on:
      - fastapi
      - redis
      - db_test

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - "./.env"   # Аналогично для бота

  db_test:
    image: postgres:17-alpine
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    env_file:
      - "./.env"

volumes:
  pgdata_test:
