services:
  alembic:
    build:
      context: .
      dockerfile: migrations/Dockerfile  # или другой путь, если alembic зависит от app
    image: alembic_image
    working_dir: /project
    volumes:
      - .:/project
    env_file:
      - "./.env"
    depends_on:
      - db

  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: api_image
    ports:
      - "8000:8000"
    env_file:
      - "./.env"
    depends_on:
      - db
      - redis
    restart: always

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    image: bot_image
    env_file:
      - "./.env"
    depends_on:
      - fastapi
      - redis
      - db
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - "./.env"
    restart: always

  db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - "./.env"
    restart: always

  backup:
    build:
      context: ./backups
    container_name: backup
    depends_on:
      - db
    volumes:
      - ./backups:/backups
    env_file:
      - "./.env"
    restart: always

volumes:
  pgdata: