"""Alter tariffs and extra_Services

Revision ID: c40f03c2b4fe
Revises: d94ed7720ac3
Create Date: 2025-08-04 05:49:26.999067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c40f03c2b4fe"
down_revision: Union[str, Sequence[str], None] = "d94ed7720ac3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("extra_services", "document_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tariffs", "document_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tariffs", "document_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("extra_services", "document_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
