"""nullable True password

Revision ID: 42ac12e67af8
Revises: 61eceb52943d
Create Date: 2025-07-03 17:38:12.392310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42ac12e67af8"
down_revision: Union[str, Sequence[str], None] = "61eceb52943d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_psw", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_psw", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###
