"""Relationship between Users and PhoneNumber

Revision ID: 939fe2236e36
Revises: 9a6e6f502db6
Create Date: 2025-07-03 16:51:38.721377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "939fe2236e36"
down_revision: Union[str, Sequence[str], None] = "9a6e6f502db6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
