"""Added access, refresh columns into Users

Revision ID: 08b9d8d17ea3
Revises:
Create Date: 2025-08-20 06:16:30.318618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08b9d8d17ea3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("extra_services", "document_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tariffs", "document_id", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column("users", sa.Column("access_token", sa.String(), nullable=True))
    op.add_column("users", sa.Column("refresh_token", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["contract_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "refresh_token")
    op.drop_column("users", "access_token")
    op.alter_column("tariffs", "document_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("extra_services", "document_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
