"""change column contractor nullable False

Revision ID: e429f63d1d9d
Revises: 1a9ab40905d0
Create Date: 2025-07-04 10:32:40.974704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e429f63d1d9d"
down_revision: Union[str, Sequence[str], None] = "1a9ab40905d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "contractor", existing_type=sa.VARCHAR(length=100), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "contractor", existing_type=sa.VARCHAR(length=100), nullable=True)
    # ### end Alembic commands ###
