"""refactor invoice table1

Revision ID: b194485b619c
Revises: b09691eb226b
Create Date: 2025-07-27 10:53:24.800988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b194485b619c"
down_revision: Union[str, Sequence[str], None] = "b09691eb226b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("telegram_file_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "telegram_file_id")
    # ### end Alembic commands ###
