"""refactor invoice table

Revision ID: b09691eb226b
Revises: 3d194010a578
Create Date: 2025-07-27 10:40:53.112054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b09691eb226b"
down_revision: Union[str, Sequence[str], None] = "3d194010a578"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("departure_city", sa.String(), nullable=False))
    op.add_column("invoices", sa.Column("recipient_city", sa.String(), nullable=False))
    op.drop_column("invoices", "file_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices", sa.Column("file_name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("invoices", "recipient_city")
    op.drop_column("invoices", "departure_city")
    # ### end Alembic commands ###
