"""Refactoring Tables

Revision ID: 61eceb52943d
Revises: 199de2663f68
Create Date: 2025-07-03 17:24:36.126717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61eceb52943d"
down_revision: Union[str, Sequence[str], None] = "199de2663f68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_name", sa.String(length=100), nullable=True),
        sa.Column("fullname", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=150), nullable=False),
        sa.Column("hashed_psw", sa.String(length=255), nullable=False),
        sa.Column("is_logged", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("phone_number", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    )
    op.drop_table("admins")
    # ### end Alembic commands ###
