"""Increase phone number length2

Revision ID: b9e8a8ab0f3f
Revises: 152656e2e43e
Create Date: 2025-07-03 16:58:32.878043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9e8a8ab0f3f"
down_revision: Union[str, Sequence[str], None] = "152656e2e43e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phone_numbers",
        "number",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phone_numbers",
        "number",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
