"""change column contractor

Revision ID: 1a9ab40905d0
Revises: f35a5ab6efe3
Create Date: 2025-07-04 10:30:05.572352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a9ab40905d0"
down_revision: Union[str, Sequence[str], None] = "f35a5ab6efe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("contractor", sa.String(length=100), nullable=True))
    op.drop_column("admins", "fullname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admins",
        sa.Column("fullname", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_column("admins", "contractor")
    # ### end Alembic commands ###
