"""change column again

Revision ID: 7e0cd302109a
Revises: 63f584cd9ad2
Create Date: 2025-07-16 14:42:32.934492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e0cd302109a"
down_revision: Union[str, Sequence[str], None] = "63f584cd9ad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "role", existing_type=sa.VARCHAR(length=10), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "role", existing_type=sa.VARCHAR(length=10), nullable=False)
    # ### end Alembic commands ###
