"""change column

Revision ID: 63f584cd9ad2
Revises: e429f63d1d9d
Create Date: 2025-07-16 14:41:18.186151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63f584cd9ad2"
down_revision: Union[str, Sequence[str], None] = "e429f63d1d9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "hashed_psw", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "hashed_psw", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###
