"""Increase phone number length

Revision ID: 152656e2e43e
Revises: 939fe2236e36
Create Date: 2025-07-03 16:55:58.618157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "152656e2e43e"
down_revision: Union[str, Sequence[str], None] = "939fe2236e36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phone_numbers",
        "number",
        existing_type=sa.VARCHAR(length=15),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phone_numbers",
        "number",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=15),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
