"""change column again1

Revision ID: 6430f0853e0e
Revises: 7e0cd302109a
Create Date: 2025-07-16 14:43:59.293239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6430f0853e0e"
down_revision: Union[str, Sequence[str], None] = "7e0cd302109a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "role", existing_type=sa.VARCHAR(length=10), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "role", existing_type=sa.VARCHAR(length=10), nullable=True)
    # ### end Alembic commands ###
