"""15

Revision ID: 199de2663f68
Revises: b9e8a8ab0f3f
Create Date: 2025-07-03 17:06:09.799432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "199de2663f68"
down_revision: Union[str, Sequence[str], None] = "b9e8a8ab0f3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phone_numbers",
        "number",
        existing_type=sa.VARCHAR(length=150),
        type_=sa.String(length=15),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phone_numbers",
        "number",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=150),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
