"""refactor invoice table3

Revision ID: 87dd555348ee
Revises: 788e1a02879f
Create Date: 2025-07-27 11:16:01.741616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87dd555348ee"
down_revision: Union[str, Sequence[str], None] = "788e1a02879f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoices",
        "invoice_number",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoices",
        "invoice_number",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
