"""Added access, refresh columns into Admins

Revision ID: 91d1e1e22f60
Revises: 08b9d8d17ea3
Create Date: 2025-08-20 12:27:32.988421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91d1e1e22f60"
down_revision: Union[str, Sequence[str], None] = "08b9d8d17ea3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("access_token", sa.String(), nullable=True))
    op.add_column("admins", sa.Column("refresh_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "refresh_token")
    op.drop_column("admins", "access_token")
    # ### end Alembic commands ###
